/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crypto.sample.java;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
